# Generated by Django 6.0.6 on 2026-06-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name': 'زیردسته',
                'verbose_name_plural': 'زیردسته\u200cها',
                'ordering': ['category', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='هشتگ')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی')], default='fa', max_length=2)),
                ('post_count', models.BigIntegerField(default=0, verbose_name='تعداد پست')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='core.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashtags', to='core.subcategory')),
            ],
            options={
                'verbose_name': 'هشتگ',
                'verbose_name_plural': 'هشتگ\u200cها',
                'ordering': ['-post_count'],
                'indexes': [models.Index(fields=['language', 'category'], name='core_hashta_languag_72d305_idx'), models.Index(fields=['post_count'], name='core_hashta_post_co_2404f0_idx')],
            },
        ),
    ]
