# Generated by Django 6.0.6 on 2026-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('endpoint', models.CharField(max_length=100, verbose_name='مسیر درخواست')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ['-created_at'],
            },
        ),
    ]
